config/routes.rb
  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :post]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  match 'my/reset_rss_key', :controller => 'my', :action => 'reset_rss_key', :via => :post
  match 'my/reset_api_key', :controller => 'my', :action => 'reset_api_key', :via => :post
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/page_layout', :controller => 'my', :action => 'page_layout', :via => :get
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post
  match 'my/reports', :controller => 'my', :action => 'reports', :via => [:get, :post]
  match 'my/generate_reports', :controller => 'my', :action => 'generate_reports', :via => [:get, :post]
  match 'my/project_reports', :controller => 'my', :action => 'project_reports', :via => [:get, :post]
  match 'my/user_reports', :controller => 'my', :action => 'user_reports', :via => [:get, :post]
  match 'my/userreport', :controller => 'my', :action => 'userreport', :via => [:get, :post]
  match 'my/projectreport', :controller => 'my', :action => 'projectreport', :via => [:get, :post]
  match 'my/finalreport', :controller => 'my', :action => 'finalreport', :via => [:get, :post]
  match 'my/timesheet', :controller => 'my', :action => 'timesheet', :via => [:get, :post]
  match 'my/mytimesheet', :controller => 'my', :action => 'mytimesheet', :via => [:get, :post]
  match 'my/logs', :controller => 'my', :action => 'logs', :via => [:get, :post]
  match 'my/issue', :controller => 'my', :action => 'issue', :via => [:get, :post]
  match 'my/add_issuetask', :controller => 'my', :action => 'add_issuetask', :via => [:put, :post]
  resources :users
  match 'users/:id/memberships/:membership_id', :to => 'users#edit_membership', :via => :put, :as => 'user_membership'
  match 'users/:id/memberships/:membership_id', :to => 'users#destroy_membership', :via => :delete
  match 'users/:id/memberships', :to => 'users#edit_membership', :via => :post, :as => 'user_memberships'

  match 'watchers/new', :controller=> 'watchers', :action => 'new', :via => :get
  match 'watchers', :controller=> 'watchers', :action => 'create', :via => :post
  match 'watchers/append', :controller=> 'watchers', :action => 'append', :via => :post
  match 'watchers/destroy', :controller=> 'watchers', :action => 'destroy', :via => :post
  match 'watchers/watch', :controller=> 'watchers', :action => 'watch', :via => :post
  match 'watchers/unwatch', :controller=> 'watchers', :action => 'unwatch', :via => :post
  match 'watchers/autocomplete_for_user', :controller=> 'watchers', :action => 'autocomplete_for_user', :via => :get

  match 'projects/:id/settings/:tab', :to => "projects#settings"
  

  
     
  
  resources :projects do
    member do
      get 'settings'
      post 'modules'
      post 'archive'
      post 'unarchive'
      match 'copy', :via => [:get, :post]
    end
	 resources :iterations do 
		resources :stories do
		  resources :tasks do
	 	    collection do 
			get 'total_tasks'
			
			
			end
		  end 
		end
  end

    resources :memberships, :shallow => true, :controller => 'members', :only => [:index, :show, :create, :update, :destroy] do
      collection do
        get 'autocomplete'
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    match 'issues/:copy_from/copy', :to => 'issues#new'
    resources :issues, :only => [:index, :new, :create] do
      resources :time_entries, :controller => 'timelog' do
        collection do
          get 'report'
        end
      end
    end
    # issue form update
    match 'issues/new', :controller => 'issues', :action => 'new', :via => [:put, :post], :as => 'issue_form'
    match 'issues/issue', :controller => 'issues', :action => 'issue', :via => [:put, :post]
    match 'issues/add_issuetask', :controller => 'issues', :action => 'add_issuetask', :via => [:put, :post]
     match 'issues/task', :controller => 'issues', :action => 'task', :via => [:put, :post]
    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do

      collection do
        put 'close_completed'
      end

    end
    match 'versions.:format', :to => 'versions#index'
    match 'roadmap', :to => 'versions#index', :format => false
    match 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog' do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create] 
    
    resources :issue_categories, :shallow => true
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    resources :repositories, :shallow => true, :except => [:index, :show] do
      member do
        match 'committers', :via => [:get, :post]
      end
    end

    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    match 'wiki/:id/diff/:version/vs/:version_from', :controller => 'wiki', :action => 'diff'
    match 'wiki/:id/diff/:version', :controller => 'wiki', :action => 'diff'
    resources :wiki, :except => [:index, :new, :create] do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    match 'wiki/:id/annotate/:version', :controller => 'wiki', :action => 'annotate'
  end

  resources :issues do
   resources :tasks
    collection do
      match 'bulk_edit', :via => [:get, :post]
      post 'bulk_update'
      post 'issue_addtask'
    end
    resources :time_entries, :controller => 'timelog' do
      collection do
        get 'report'
      end
    end
    resources :relations, :shallow => true, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
  end
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]

  resources :news, :only => [:index, :show, :edit, :update, :destroy]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

  match '/time_entries/context_menu', :to => 'context_menus#time_entries', :as => :time_entries_context_menu

  resources :time_entries, :controller => 'timelog', :except => :destroy do
    collection do
      get 'report'
      get 'bulk_edit'
      post 'bulk_update'
    end
  end
  match '/time_entries/:id', :to => 'timelog#destroy', :via => :delete, :id => /\d+/
  # TODO: delete /time_entries for bulk deletion
  match '/time_entries/destroy', :to => 'timelog#destroy', :via => :delete

  # TODO: port to be part of the resources route(s)
  match 'projects/:id/settings/:tab', :to => 'projects#settings', :via => :get

  get 'projects/:id/activity', :to => 'activities#index'
  get 'projects/:id/activity.:format', :to => 'activities#index'
  get 'activity', :to => 'activities#index'

  # repositories routes
  get 'projects/:id/repository/:repository_id/statistics', :to => 'repositories#stats'
  get 'projects/:id/repository/:repository_id/graph', :to => 'repositories#graph'

  get 'projects/:id/repository/:repository_id/changes(/*path(.:ext))',
      :to => 'repositories#changes'

  get 'projects/:id/repository/:repository_id/revisions/:rev', :to => 'repositories#revision'
  get 'projects/:id/repository/:repository_id/revision', :to => 'repositories#revision'
  post   'projects/:id/repository/:repository_id/revisions/:rev/issues', :to => 'repositories#add_related_issue'
  delete 'projects/:id/repository/:repository_id/revisions/:rev/issues/:issue_id', :to => 'repositories#remove_related_issue'
  get 'projects/:id/repository/:repository_id/revisions', :to => 'repositories#revisions'
  get 'projects/:id/repository/:repository_id/revisions/:rev/:action(/*path(.:ext))',
      :controller => 'repositories',
      :constraints => {
            :action => /(browse|show|entry|raw|annotate|diff)/,
            :rev    => /[a-z0-9\.\-_]+/
          }

  get 'projects/:id/repository/statistics', :to => 'repositories#stats'
  get 'projects/:id/repository/graph', :to => 'repositories#graph'

  get 'projects/:id/repository/changes(/*path(.:ext))',
      :to => 'repositories#changes'

  get 'projects/:id/repository/revisions', :to => 'repositories#revisions'
  get 'projects/:id/repository/revisions/:rev', :to => 'repositories#revision'
  get 'projects/:id/repository/revision', :to => 'repositories#revision'
  post   'projects/:id/repository/revisions/:rev/issues', :to => 'repositories#add_related_issue'
  delete 'projects/:id/repository/revisions/:rev/issues/:issue_id', :to => 'repositories#remove_related_issue'
  get 'projects/:id/repository/revisions/:rev/:action(/*path(.:ext))',
      :controller => 'repositories',
      :constraints => {
            :action => /(browse|show|entry|raw|annotate|diff)/,
            :rev    => /[a-z0-9\.\-_]+/
          }
  get 'projects/:id/repository/:repository_id/:action(/*path(.:ext))',

app/models/iteration.rb
class Iteration < ActiveRecord::Base
  belongs_to :project
  has_many :story
  attr_accessible :description, :end_date, :name, :start_date,:status, :iterationtype
  validates_presence_of :end_date, :name, :start_date, :iterationtype
  #validates :name, :uniqueness => {:case_sensitive => false}

end

app/controllers/iterations_controller.rb
class IterationsController < ApplicationController
#before_filter :test, :except => [:index, :new, :edit, :show]

def test
@project = Project.find(params[:project_id])	
@new_params = params[:iteration]
raise @new_params.each_value { |key| puts "#{key}" }.inspect
flag = 0
@project.iteration.each do |it|
@endd = it.end_date
if @enddate < @endd
flag += 1
else
flag = 0
end
end
if flag == 0
redirect_to "create"
else
raise "you selecting date is already there".inspect
end
end

def index
    @project = Project.find(params[:project_id])
    @iterations = Iteration.find(:all)
end

def new
    @project = Project.find(params[:project_id])
    @iteration = @project.iteration.new

end

def edit
    @project = Project.find(params[:project_id])
    @iteration = @project.iteration.find(params[:id])
end

def create
	  @project = Project.find(params[:project_id])
		 @iteration = @project.iteration.new(params[:iteration])

	if @iteration.status == "Open"
		@all_iterations = Iteration.find(:all, :select => "status" ,:conditions => {:status => "Open", :project_id => @project.id}).map(&:status).count
	#raise @all_iterations.inspect
	if @all_iterations >= 1
		flash[:error] ="one iteration is already opened. please select planned"
		redirect_to new_project_iteration_path(@project.id) and return
	else
		@all_enddates = Iteration.find(:all, :select => "end_date" ,:conditions => {:project_id => @project.id}).map(&:end_date)
	if @all_enddates == []
		@iteration.save
		redirect_to project_iteration_path(@project.id, @iteration.id ) and return
	else
		@all_enddates.each do |end_date|
	if @iteration.start_date > end_date
		@iteration.save
		redirect_to project_iteration_path(@project.id, @iteration.id ) and return
	else
		flash[:error] ="Please select differenct dates"
		redirect_to new_project_iteration_path(@project.id) and return
	end
	end
	end
	end
	else
	@all_enddates = Iteration.find(:all, :select => "end_date" ,:conditions => {:project_id => @project.id}).map(&:end_date)
	if @all_enddates == []
	@iteration.save
	redirect_to project_iteration_path(@project.id, @iteration.id ) and return
	else
	@all_enddates.each do |end_date|
	if @iteration.start_date > end_date
	@iteration.save
	redirect_to project_iteration_path(@project.id, @iteration.id ) and return
	else
	flash[:error] ="Please select differenct dates"
	redirect_to new_project_iteration_path(@project.id) and return
	end
	end
	end

	end
end

def update
   @project = Project.find(params[:project_id])
   @iteration = @project.iteration.find(params[:id])

   if @iteration.update_attributes(params[:iteration])
if @iteration.status == "Closed"
raise "yes ".inspect
end
       render :action => "show"
   else
       render :action => "edit"
   end
 end

def show
    @project = Project.find(params[:project_id])
    @iteration = @project.iteration.find(params[:id])
    render :action => "show"
end
end

app/views/iterations/_form.html.erb
<html>

<% @flag = 0 %>

<p> New Iteration for project -> <b><%= @project.name %></b> </p>
<div id ="new_look">
<table >

<%= form_for([@project, @project.iteration.build]) do |f| %>
 <tr>
    <td id="tdleft"><%= f.label :name %></td>
    <td><%= f.text_field :name %></td>
 </tr>
  <tr>
	 <td id="tdleft"><%= f.label :iterationtype %></td>	  
     <td><%= f.select(:iterationtype, options_for_select(["Weekly", "Monthly", "BIO-Monthly"])) %>
  </td>
 </tr>
  <tr>
	 <td id="tdleft"><%= f.label :Start_date %></td>
     <td><%= f.text_field :start_date, :id => :popupDatepicker , :onmouseout=> "myFunction()"%></td>
    </tr>
  <tr>
	  
    <td id="tdleft"><%= f.label :End_date %></td>
   
   <td> <%= f.text_field :end_date, :id => :popupDatepicker1 %></td>
  </tr>
  <tr>
    <td id="tdleft"><%= f.label :Status %></td>
   <td><%= f.select(:status, options_for_select(["Planned","Open"])) %></td>
   </tr>
<tr><td id="tdleft">
    <%= f.label :Description %></td>
    <td>    <%= f.text_area :description%></td>
   </tr></div>
  <tr><td>
    <%= f.submit %></td></tr>
  
<% end %>
 </table>

</html>
<script>
$("#popupDatepicker").glDatePicker(
{
onChange: function(target, newDate)
{
target.val
(
	newDate.getFullYear() + "-" +
	(newDate.getMonth() + 1) + "-" +
	newDate.getDate()
);
}
});
$("#popupDatepicker1").glDatePicker(
{
onChange: function(target, newDate)
{
target.val
(
	newDate.getFullYear() + "-" +
	(	newDate.getMonth() + 1) + "-" +
	newDate.getDate()
);
}
});
</script>
<script>
 function myFunction()
 {
var current_ele = $("#iteration_iterationtype").val();
if(current_ele == "Weekly")
{	
	var st_date = $("#popupDatepicker").val();
	var date1 = Date.parse(st_date);
	date1.setDate(date1.getDate() + 7);
	var testda = date1.toString("yyyy-MM-dd");
	$("#popupDatepicker1").val(testda);
}else
if(current_ele == "Monthly")
{
	var st_date = $("#popupDatepicker").val();
	var date1 = Date.parse(st_date);
	date1.setDate(date1.getDate() + 30);
	var testda = date1.toString("yyyy-MM-dd");
	$("#popupDatepicker1").val(testda);
}
else
{
	var st_date = $("#popupDatepicker").val();
	var date1 = Date.parse(st_date);
	date1.setDate(date1.getDate() + 15);
	var testda = date1.toString("yyyy-MM-dd");
	$("#popupDatepicker1").val(testda);
}
 }
</script>
<style>
	#new_look{background: #F5FCFC;  border-radius: 5px 5px 5px 5px;
    margin-left: 50px;
    max-width: 65%;}
    #tdleft{float: right; top: 9px; position: relative;}
    textarea {
    resize: none;
    cols: 20;
    rows: 40;
    width: 462px; height: 214px;
    }
	</style>

app/views/iterations/edit.html.erb
<%= stylesheet_link_tag( 'default')%>
<%= javascript_include_tag('jquery.min', 'glDatePicker.min', 'date')%>
<h1>Editing Iteration</h1>
<% @flag = 0 %>
<html>
<p> New Iteration for <b><%= @project.name %></b> </p>
<table border="1" >
<tr>
<%= form_for @iteration , :url => {:action => :update, :id => @iteration.id } do |f| %>
 <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    
    <%= f.select(:iterationtype, options_for_select(["Weekly", "Monthly", "BIO-Monthly"]), {}, {:disabled => true}) %>
  </div>
  <div class="field">
    <%= f.label :Start_date %><br />
    <%= f.text_field :start_date, :id => :popupDatepicker , :onmouseout=> "myFunction()", :disabled => "true"%>
  </div>
  <div class="field">
    <%= f.label :End_date %><br />
    <%#= f.date_select :end_date %>
    <%= f.text_field :end_date, :id => :popupDatepicker1 , :disabled => "true"%>
  </div>
   <div class="field">
    <%= f.label :Status %><br />
 <%= f.select(:status, options_for_select(["Planned","Open"]), {}, {:disabled => true}) %>


  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</tr>
 </table>
</html>

<script>
	$("#popupDatepicker").glDatePicker(
	{
		onChange: function(target, newDate)
		{
			target.val
			(
				newDate.getFullYear() + "-" +
				(newDate.getMonth() + 1) + "-" +
				newDate.getDate()
			);
		}
	});
	$("#popupDatepicker1").glDatePicker(
	{
		onChange: function(target, newDate)
		{
			target.val
			(
				newDate.getFullYear() + "-" +
				(newDate.getMonth() + 1) + "-" +
				newDate.getDate()
			);
		}
	});
</script>

app/views/iterations/index.html.erb
<html>
<head>
<script>
function load()
{
var str = 0
var id =0 
	<% @iterations.each do |t| %>
			<% if t.status == "Closed" %>
			str+=1
			id = t.id
			<% end %>
			if (str > 0)
				{
					alert(id);
				}
			else
				{
					alert("no");
				}
	<% end %>

}
</script>
</head>
<body  >
<table >
	<h2> <%= @project.name %> </h2>
		<p><b>List of Iterations</b></p>
	
		<tr width="900px">
			<th width ="200px">Name</th>
			<th width ="500px">IterationType</th>
			<th width ="100px">Start_date</th>
			<th width ="100px">End_date</th>
			<th width ="500px">Description</th>	
		
			<th width ="500px">Edit</th>
		</tr>
		<%@project.iteration.each do |it| %>
  		
			<tr width="900px" align="center" id = "#{it.id}" >
				<td width ="200px">
					<%= link_to it.name, project_iteration_path(@project.id, it.id) %>
				</td>
				<td width ="100px">
					<%= it.iterationtype %>
				</td>
				<td width ="100px">
					<%= it.start_date %>
				</td>
				<td width ="100px">
					<%= it.end_date %>
				</td>
				<td width ="500px">
					<%= it.status %>
				</td>
  					<td><%= link_to "edit", edit_project_iteration_path(@project.id, it.id) %></td>
			</tr>
		<% end %>
</table>
<%if User.current.admin?  %>
	<%= link_to "New Iteration",  new_project_iteration_path(@project.id) %>
<%end %>

</body>
</html>

app/views/iterations/new.html.erb
<%= stylesheet_link_tag( 'default')%>
<%= javascript_include_tag('jquery.min', 'glDatePicker.min', 'date')%>
<%= render 'form' %>

app/views/iterations/show.html.erb
<html>
 <h2><%= link_to @project.name, project_path(@project) %> >> <%= @iteration.name %></h2>
<table>
<tr>

<td>
Name:
</td>
<td>
<%= @iteration.name %>
</td>
</tr>
<tr>

<td>
Iteation Type:
</td>
<td>
<%= @iteration.iterationtype %>
</td>
</tr>
<tr>
<td>
Start_date
</td>
<td>
<%= @iteration.start_date %>
</td>
</tr>
<tr>
<td>
End_date
</td>
<td>
<%= @iteration.end_date %>
</td>
</tr>
<tr>
<td>
Status
</td>
<td>
<%= @iteration.status %>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
<%= @iteration.description %>
</td>
</tr>
</table>
<%#= @project.id %>
<%#= @iteration.id %>
<%= link_to "users_stories", project_iteration_stories_path(@project.id, @iteration.id )%>
</html>